name: Flutter Build All Platforms

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          
      - name: Build APK
        run: |
          flutter pub get
          flutter build apk --release
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod setup
          
      - name: Build iOS
        run: |
          flutter pub get
          cd ios
          pod install
          cd ..
          flutter build ios --release --no-codesign
          
      - name: Upload iOS Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: build/ios/Release-iphoneos/

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          cache: true
          
      - name: Enable Windows Platform
        run: flutter create --platforms=windows .
          
      - name: Upgrade Dependencies
        run: |
          flutter pub upgrade --major-versions
          flutter pub get
          
      - name: Build Windows
        run: |
          flutter clean
          flutter build windows --release
          
      - name: Verify Build Output
        run: dir build\windows\runner\Release
          
      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: build/windows/runner/Release

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            cmake \
            ninja-build \
            pkg-config \
            libgtk-3-dev \
            libmpv-dev \
            mpv
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          
      - name: Build Linux
        run: |
          flutter pub upgrade
          flutter clean
          flutter build linux --release
          
      - name: Upload Linux
        uses: actions/upload-artifact@v4
        with:
          name: linux-app
          path: build/linux/x64/release/bundle

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          
      - name: Build macOS
        run: |
          flutter pub get
          flutter build macos --release
          
      - name: Upload macOS
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: build/macos/Build/Products/Release/*.app